sfdc.url=https://orgfarm-9f6f35f4a3-dev-ed.develop.my.salesforce.com/services/data/v61.0/sobjects/Case
# corrected property name: sfdc.token (was sfdc.tokn)
sfdc.token=00Dfj00000QTG0n!AQEAQOcm6GR9qAU1rEx8IL.XDZGn9b5VuRHI602KXBBhtdbfUyjUnB4713MX3xffTvinHNKTbVqqriRdOdjieXyfqhEv.TKJ
server.port=${PORT:8090}
