sfdc.url=https://orgfarm-9f6f35f4a3-dev-ed.develop.my.salesforce.com/services/data/v61.0/sobjects/Case
# corrected property name: sfdc.token (was sfdc.tokn)
sfdc.token=${SFDC_TOKEN}
server.port=${PORT:8080}
